import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "@/components/Navbar";
import { roboto, suwannaphum } from "./font";
import Footer from "@/components/Footer";
import StoreProvider from "./storeProvider";
import SessionWrapper from "./SessionWrapper";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<SessionWrapper>
				<body className={`${suwannaphum.variable} ${roboto.variable}`}>
					<StoreProvider>
						<Providers>
							<Navbar />
							{children}
							<ToastContainer />
							<Footer />
						</Providers>
					</StoreProvider>
				</body>
			</SessionWrapper>
		</html>
	);
}
